<?php

/**
 * @file
 * Provides integration with the AOS library.
 */

/**
 * Implements hook_help().
 */
function aos_help($path, $arg) {
  switch ($path) {
    case 'admin/help#aos':
      return '<p>' . t('<a href="@aos" target="_blank">Animate On Scroll</a> is a small library to animate elements on your page as you scroll. It allows you to animate elements as you scroll down, and up. If you scroll back to top, elements will animate to it\'s previous state and are ready to animate again if you scroll down.', [
          '@aos' => 'https://michalsnik.github.io/aos/',
        ]) . '</p>';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function aos_library_info_alter(&$libraries, $module) {
  if ($module == 'aos') {
    // In case that the libraries are included locally, use those instead of the
    // CDN.
    // @see https://www.drupal.org/node/3099614
    $library_file_finder = \Drupal::service('library.libraries_directory_file_finder');

    $path = $library_file_finder->find('aos/aos.js');
    if ($path) {
      $libraries['aos']['js'] = [
        '/' . $path => ['minified' => TRUE]
      ];
    }
    $path = $library_file_finder->find('aos/aos.css');
    if ($path) {
      $libraries['aos']['css'] = [
        'theme' => [
          '/' . $path => ['minified' => TRUE]
        ]
      ];
    }
  }
}
