_core:
  default_config_hash: xu0yG13sSQJcXrOJJqsn44W_hUWAIFHVlphrzxT2ycU
page_title: Sitemap
message:
  value: ''
  format: plain_text
plugins:
  frontpage:
    enabled: true
    weight: 0
    settings:
      title: 'Front page'
      rss: /rss.xml
    id: frontpage
    provider: sitemap
include_css: true
